package br.com.gvt.eng.vod;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Envivio 4Balancer
 * 
 * This class was generated by Apache CXF 2.4.6 2014-11-10T16:27:29.555-02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "Envivio_4Balancer_Service", wsdlLocation = "http://177.16.28.166/balancerSOAP?WSDL", targetNamespace = "urn:envivio:balancer:1.0")
public class Envivio4BalancerService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("urn:envivio:balancer:1.0",
			"Envivio_4Balancer_Service");
	public final static QName Service = new QName("urn:envivio:balancer:1.0",
			"Service");
	static {
		URL url = null;
		try {
			url = new URL("http://177.16.28.166/balancerSOAP?WSDL");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(
					Envivio4BalancerService.class.getName()).log(
					java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}",
					"http://177.16.28.166/balancerSOAP?WSDL");
		}
		WSDL_LOCATION = url;
	}

	public Envivio4BalancerService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public Envivio4BalancerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Envivio4BalancerService() {
		super(WSDL_LOCATION, SERVICE);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// compliant code instead.
	public Envivio4BalancerService(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// compliant code instead.
	public Envivio4BalancerService(URL wsdlLocation,
			WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// compliant code instead.
	public Envivio4BalancerService(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns ServicePortType
	 */
	@WebEndpoint(name = "Service")
	public ServicePortType getService() {
		return super.getPort(Service, ServicePortType.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ServicePortType
	 */
	@WebEndpoint(name = "Service")
	public ServicePortType getService(WebServiceFeature... features) {
		return super.getPort(Service, ServicePortType.class, features);
	}

}
